### ISSUE TITLE
Can't Load Save File

### ISSUE THREAD

**Issue by lizzenz** [Theray070696/RoR2TierSelection#1]
Hey bud I've been using your plugin a lot, Love it, but I think you might have broken it somewhere, I've tried to delete all other mods and plugin's "tested" but it only seems to happen when I install the new version that came out today, It won't load my save file and puts me on the create an account screen, but the game act's frozen so you can't create or refresh. If you have a solution or find out anything please let me know, Hope you have a great day :1st_place_medal:

**Comment by Theray070696** [comment]
I'm unable to replicate this issue on my end, could you please attach either a text file or a screenshot of your BepInEx console?

**Comment by lizzenz** [comment]
Considering no one else has the issue either I'm guessing it just a missing file or something like that on my end. I'll just wait for the next update and fix it then :sweat_smile:
