### ISSUE TITLE
Fixing colors when tier is changed

### ISSUE THREAD

**Issue by kylewill0725** [Theray070696/RoR2TierSelection#3]
Are you accepting pull requests? I've been able to successfully generate the approximately correct texture at runtime.
![Tier2_4](https://user-images.githubusercontent.com/18157392/89721497-e1d5c000-d9a3-11ea-8de9-1db9db5e1739.png)

**Comment by Theray070696** [comment]
Absolutely! As long as it works well, I'll accept it.

**Comment by kylewill0725** [comment]
Thought it was working as the images I had dumped for testing looked good but it looks like UnbundledResourceProvider from R2Api doesn't support multiple asset types with the same resource path yet. This is needed as ItemDef loads both the Sprite and Texture from the same path. Working on a pull request for R2Api but it may take a bit for it to hit release.

**Comment by Theray070696** [comment]
Resolved in latest build
